### ISSUE TITLE
Creating private routes.

### ISSUE THREAD

**Issue by bigardone** [alexfedoseev/isomorphic-comments-app#1]
Hi!
First of all thank you for sharing your awesome generator.
I'm creating a new application very similar to this, but instead of comments I'm showing contact people and I'm trying to make the show route of the comments private so only authenticated users can access it.
This is what I have done so far in the routes.jsx:

```html
...
<Route name="person"      path="/people/:id"  component={Person} context={context} onEnter={Person.DecoratedComponent.checkAuth}/>
...
```
And this is the check auth method in the PersonContainer component:

```javascript
...
static checkAuth(nextState, transition) {
    console.log('Checking');

    const { auth } = this.context.store.getState();
    if (!auth.isLoggedIn) transition.to('/');
  }
...
```
The thing is that when running the ```npm start``` command, and reloading the browser, it hangs and never ends loading, so I can't even see if there's been an error.

Is this the correct approach to achieve what I need or is there a better one?
Thank you very much in advance.

**Comment by alexfedoseev** [comment]
Hi!

Looks like you don't handle abort of transition on server.
Here is example of such handler: https://github.com/alexfedoseev/isomorphic-comments-app/blob/master/app/libs/initters/server.jsx#L60

**Comment by bigardone** [comment]
Hi, thanks for your response.
I have the same ```server.jsx``` which was created by the generator.
https://github.com/bigardone/redux-test-app/blob/feature/private-route-error/app/libs/initters/server.jsx#L60

I have uploaded the project to github, and here is the commit with the changes I did:
https://github.com/bigardone/redux-test-app/commit/6826792f5e1c61e3b4f348c2b9a5f9c854c48adf

If removing this it works perfectly, and if I try the checkAuth of the ```login``` route it redirects to root.
But when adding the same functionality to any other route it makes the server hang and to throw a timeout.

Is there anything I'm missing apart from those changes to make this work?

Thanks again and sorry for any inconvenience.

**Comment by alexfedoseev** [comment]
I think we need to expose `DecoratedComponent` in `fetchData` decorator.
Try to apply these changes: https://github.com/bigardone/redux-test-app/pull/1
Write me back if it works or not.

**Comment by bigardone** [comment]
Hey @alexfedoseev that did actually work, thank you very much :)

**Comment by alexfedoseev** [comment]
You're welcome :+1:
